### PR TITLE
tech(util/base) : add localization

### PR DESCRIPTION
**Pull request by govindarajkp**
1. npm install --save react-i18next i18next
2.Create the folders structure under 
  src folder 
  +-- i18n
      +-- locales
      |    +-- en
      |        +-- translations.json
      +-- config.js
3. update config.js file for the necessary  configuration 

Please follow the steps which is mentioned on the below URL :
https://www.freecodecamp.org/news/how-to-add-localization-to-your-react-app/

### CODE REVIEW

**Review by shangan23 — APPROVED** [review]
lgtm

**Review by shangan23 — CHANGES_REQUESTED** [review]
add a sample en.json file along with i18n PR. @govindarajkp

**Comment by govindarajkp** [comment]
> add a sample en.json file along with i18n PR. @govindarajkp

Added JSON file along with implementation on the menu component.

**Review by shangan23 — CHANGES_REQUESTED** [review]
can you implement i18n in any component and update pls, also maintain commit message in lower case

**Review by shangan23 — APPROVED** [review]
lgtm

**Pull request merged**
